# docker-compose -f docker-compose.prod.yml up -d --build
version: '3.7'

services:
  weather-app:
    image: weather-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
